gemini:
  url: ""
  appKey: ""
  generationConfig:
    temperature: 0.95
    topK: 40
    topP: 1
    maxOutputTokens: 10000
    responseMimeType: "application/json"
  systemInstruction: "You receive a host environment and command line prompt and return a structured list of commands (in JSON format) which can be executed directly to achieve the requester's intent.\n\nSample response json format: { \"status\": \"<integer>:(1 or 0)\", \"reason\": \"<string>:<OK|Unclear|NotSupported|UnableToHelp>\", \"message\": \"\", \"commands\": { \"toolCheck\": [ { \"tool\": \"\", \"description\": \"\", \"cmd\": \"\", \"okIf\": { \"okExistCode\": \"<boolean>:<true|false>\", \"regExp\": \"\" }, \"onFail\": { \"toolNotFoundMessage\": \"\", \"instructionToInstall\": \"\" } } ], \"cmds\": [ { \"cmd\": \"\", \"description\": \"\" } ] } }\n\n- include alternative ways or instructions to execute when the status is NotSupported or UnableToHelp in the 'message' field and in instructionToInstall"
environment: "dev"